### PR TITLE
Improve formatting and toolbar visibility consistency

### LINKED ISSUE #19: Inline Menu - Keep open after styling
The inline menu shows up when you have selected text and should remain open if you select an option from the inline menu. It's weird to need to reselect it. The user may want to select bold and italic in one shot. It may also be confusing to not see the menu anymore.

### PR DESCRIPTION
**Pull request by charrondev**
Closes https://github.com/vanilla/rich-editor/issues/19
Closes https://github.com/vanilla/vanilla/issues/7516

## Testing

There is a lot of automated testing added for https://github.com/vanilla/vanilla/issues/7516. There are specific acceptance criteria and reproduction steps for some specific issue outlined there.

https://github.com/vanilla/rich-editor/issues/19 is a bit more open ended. A few things that I've done manual verification of are:

- Keyboard shortcuts for navigating the menu items.
- All inline formats can be applied in a row without the menu closing.
- The menu still closes when clicking away.
- The escape key still closes the inline menu, and clears the current selection (by placing cursor at the end).
- The escape closes the link menu if it is open.
- Paragraph menu can be used to format multiple lines.
- Inline menu is closed when there are multiple lines selected.

## Implementation details

I was initial trying to start with just https://github.com/vanilla/vanilla/issues/7516, but that required an accurate lastGoodSelection at all times. Once that was available in the toolbars they no longer needed to know anything about quill maintaining its state at all.

So:

### Formatter class

There is now a dedicated formatter class. This enables much easier testing and has support for every format that we currently offer. I've added 100s of tests in the PR for applying these formats to be consistent with the success criteria defined in

### Cleanup of InlineToolbar

The inline toolbar now gets most of its data (except focus and input state) through props. The Quill event listeners have been removed. This now uses the same single source of truth for its selection position as the Paragraph toolbar.

Implements the spec defined in https://github.com/vanilla/rich-editor/issues/19#issuecomment-409651909

### Paragraph toolbar

Implements the spec defined in https://github.com/vanilla/rich-editor/issues/19#issuecomment-409651909

### Cleanup of menu items

I re-organized the menu items to be:

- Defined more simply. There is no longer special parsing done to get them in the correct order and they no longer keep state of what is enabled. Instead each item must provide an isEnabled function. This is normally a simple equality check with the formats provided in Redux.
- Have no knowledge of Quill.
- Updated the paragraph menu toolbar buttons to have a role of `menuitemradio` and used `aria-checked` instead of `menuitem` and `aria-pressed`.
- Have links to ARIA docs on menu items.
- MenuItems no longer queries the document using querySelector. Instead react refs to the MenuItem component are used.
- The logic for focusing through menu items now lives in the `MenuItems` component.
- The div with `role="menu"` now has the `aria-orientation` attribute as well.
- The paragraph menu still opens according to  the ARIA menu item spec, it just uses a ref to the `MenuItems` component instead.

### CODE REVIEW

**Review by slafleche — CHANGES_REQUESTED** [review]
Looks good!

I think it would be better to set the cursor at the end of your selection after selecting an element from the paragraph menu, since right after clicking on a menu, you get another one showing up.

Hitting escape on the paragraph menu should be similar to hitting escape for the inline menu

If you have some text on one line and a new line afterwards, it is possible to drag select from the end of the first line to the second and get no selection and get an inline menu show up.

Also, the `code` block should be the outermost element when multiple inline styles are applied. It's the opposite order to the server rendered version.

**Comment by charrondev** [comment]
> I think it would be better to set the cursor at the end of your selection after selecting an element from the paragraph menu, since right after clicking on a menu, you get another one showing up.

Done.

> Hitting escape on the paragraph menu should be similar to hitting escape for the inline menu

Done. The focus still goes back to the paragraph menu for accessibility purposes, but the selection is selection is moved to to the end of itself similar to the inline menu.

Of course naturally, when the button is then selected and the editor loses focus, the cursor is removed from the contenteditable.

> If you have some text on one line and a new line afterwards, it is possible to drag select from the end of the first line to the second and get no selection and get an inline menu show up.

Done. I now check for an empty (newline only selection) before showing the toolbar.

> Also, the code block should be the outermost element when multiple inline styles are applied. It's the opposite order to the server rendered version.

Also handled.

**Review by slafleche — CHANGES_REQUESTED** [review]
Set cursor at end of selection when hitting escape when paragraph menu is open

Set active paragraph button to disabled, so you can't click on it.

**Comment by charrondev** [comment]
> Set cursor at end of selection when hitting escape when paragraph menu is open

Done. I've also fixed the toggle button so that it works now.

> Set active paragraph button to disabled, so you can't click on it.

**Pull request merged**
